[project]
name = "jose"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-ollama>=1.0.1",
    "pyperclip>=1.11.0",
    "requests>=2.32.0",
    "certifi>=2024.0.0",
]
